image: ruby:latest

before_script:
    - which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )
    - eval $(ssh-agent -s)
    - ssh-add <(echo -e "$SSH_PRIVATE_KEY")
    - gem install capistrano

stages:
    - deploy

staging:
    stage: deploy
    script:
        - cap staging deploy user=${GITLAB_USER_EMAIL} branch=main
    only:
        - develop

production:
    stage: deploy
    script:
        - cap production deploy user=${GITLAB_USER_EMAIL} branch=prod
    only:
        - tags
