image: ruby:latest

before_script:
    - which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )
    - eval $(ssh-agent -s)
    - echo "$DEPLOY_PRIVATE_KEY" | base64 -d | ssh-add -
    - gem install capistrano

stages:
    - deploy

staging:
    stage: deploy
    script:
        - cap staging deploy user=${GITLAB_USER_EMAIL} branch=main
    only:
        - main

production:
    stage: deploy
    script:
        - cap production deploy user=${GITLAB_USER_EMAIL} branch=prod
    only:
        - prod
