version: "3"

services:
  app:
    build:
      context: .
      dockerfile: ./docker/prod.Dockerfile
    env_file:
      - .env.prod
  web:
    build:
      context: .
      dockerfile: ./docker/nginx.Dockerfile
    depends_on:
      - app
    ports:
      - 80:80
