
default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  adapter: postgresql
  encoding: unicode
  database: biosmart_dev
  host: db
  pool: 5
  username: 'postgres'
  password: 'oBa5UiDLZM'

test:
  <<: *default
  database: db/test.sqlite3

staging:
  <<: *default
  database: db/staging.sqlite3

production:
  adapter: postgresql
  encoding: unicode
  database: production
  host: localhost
  pool: 5
  username: 'postgres'
  password: 'biosmart'
