
default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

#default: &default
#  adapter: postgis
#  encoding: unicode
#  pool: 10
#  username: 'postgres'
#  password: 'postgres'
#  database: 'biosmart'
#  port: 5432
#  sslmode: 'prefer'

development:
  <<: *default
  database: db/development.sqlite3

test:
  <<: *default
  database: db/test.sqlite3

production:
  <<: *default
  database: db/production.sqlite3
